/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package com.mycompany.exceptionhandling;

/**
 *
 * @author Student
 */
public class nestedtryblocks {
    public static void main(String args[]){
        try{
            int a=args.length;//try a=0, a=1, and a=2 as well
            int b=4334/a;//this statement will generate a divide-by-zero exception
            System.out.println("a = "+a);
            try{//nested try block
                /*if a=1, then an divide-by-zero exception will be generated by the */
                if(a==1) {
                    a=a/(a-a);
                }//divisible by 0
                 /* if as=2 then generate an out-of-bound exception*/
                if(a==2){
                    int c[] = new int[1];
                    c[42]=99;
                }
            }
            catch(ArrayIndexOutOfBoundsException e){
                System.out.println("ArrayIndexOutOfBoundException ");
            }
        }
        catch(ArithmeticException e){
            System.out.println("Arithmetic Exception");
        }        
    }  
}
